[package]
name = "alc-lisp"
version = "0.1.0"
edition = "2021"
default-run = "alc-lisp"

[dependencies]
anyhow = "1.0.93"
bytes = "1.8.0"
clap = { version = "4.5.21", features = ["derive"] }
defer = "0.2.1"
